trigger:
- none

pool: server

steps:
- task: MLPublishedPipelineRestAPITask@0
  inputs:
    azureSubscription: 'msdn-amlws'
    PipelineId: 'dfe6f291-c6cd-4970-bd7f-60d203985cc3'
    ExperimentName: 'nyc_automl'
  displayName: 'Run automl training pipeline'
