train_environment_name = 'greentaxi_train_env'
inference_environment_name = 'greentaxi_inference_env'
model_name = 'greentaxi_lgbm_pkl'
model_name_automl = 'greentaxi_lgbm_pkl_automl'
service_name = 'greentaxisvc'
service_name_automl = 'greentaxisvcautoml'
experiment_name = 'greentaxi_experiment'
data_experiment_name = 'greentaxi_data_process'
