name: nyctaxi-train-env
channels:
- conda-forge
- anaconda
dependencies:
- python=3.6.9
- scikit-learn=0.22
- numpy=1.17.4
- pandas=0.25.3
- joblib=0.13.2
- scipy=1.3.2
- lightgbm=2.3.0
- pip:
  - azureml-core==1.0.81
  - azureml-telemetry==1.0.81
  - azureml-train-core==1.0.81
  - azureml-dataprep[fuse]
